### ISSUE TITLE
Cannot load model (eclipse linked folder)

### ISSUE THREAD

**Issue by danim-hub** [telosys-tools-bricks/telosys-tools-api#1]
I'm using telosys tools, and it has been working fine.

Now, I relocated the projects out of the eclipse workspace, and into my sources folder.

Old location was into c:\users\me\Documents\workspace-planner-3.9.2\planner-node-api,  and now I have moved and reimporte the project from c:\wc\planner\app\planner-node-api.

When I double-click the dbrep file I get the following message, it worked fine before moving the project.  It is the only file that cannot be opened, so I think it has to be with the mapping from project paths to actual paths in the specified class.

Am I doing something wrong, or it is a know issue?  I'm going to link the old path to the new in order to do my work, but I thought you should know about the issue.   I had not debugged yet  the source specified,  as I have never done eclipse plugins dev.

Regards.

Cannot load model
Exception org.telosys.tools.commons.TelosysToolsException
at org.telosys.tools.api.GenericModelLoader.loadModel (line 88)

**Comment by AlvinRadeka** [comment]
I have the same issue. In my case, I was importing old project (was using Telosys 2.1.6) in a recently installed machine. Telosys I'm using now is version 3.0.0, so I'm not sure whether it's the clean install or the different version that caused the error.
The error message said:
`Cannot load model`
`Exception org.telosys.tools.commons.TelosysToolsException : File '~~/~~/TelosysTools/MYSQL.dbrep' not found`
`at org.telosys.tools.api.GenericModelLoader.loadModel (line 88)`

In another window:
`Cannot get Database Model, current model is null`

**Comment by l-gu** [comment]
Fixed in Eclipse Plugin ver 3.1.2
